// <auto-generated />
using System;
using ASO.Infra.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ASO.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251109165308_AddFriendshipSystem")]
    partial class AddFriendshipSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ASO.Domain.AI.Entities.GeneratedAIContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("generated_AI_content", (string)null);
                });

            modelBuilder.Entity("ASO.Domain.Game.Entities.Ancestry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Backstory")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("backstory");

                    b.Property<int>("Displacement")
                        .HasColumnType("integer")
                        .HasColumnName("displacement");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<float>("Size")
                        .HasColumnType("real")
                        .HasColumnName("size");

                    b.HasKey("Id");

                    b.ToTable("ancestries", (string)null);
                });

            modelBuilder.Entity("ASO.Domain.Game.Entities.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AncestryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Backstory")
                        .HasColumnType("text")
                        .HasColumnName("backstory");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("TypeCharacter")
                        .HasColumnType("integer")
                        .HasColumnName("type_character");

                    b.HasKey("Id");

                    b.HasIndex("AncestryId");

                    b.HasIndex("ImageId");

                    b.ToTable("characters", (string)null);
                });

            modelBuilder.Entity("ASO.Domain.Game.Entities.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("classes", (string)null);
                });

            modelBuilder.Entity("ASO.Domain.Game.Entities.Friendship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<Guid>("AddresseeId")
                        .HasColumnType("uuid")
                        .HasColumnName("addressee_id");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rejected_at");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("AddresseeId");

                    b.HasIndex("RequesterId");

                    b.HasIndex("Status");

                    b.HasIndex("RequesterId", "AddresseeId")
                        .IsUnique();

                    b.ToTable("friendships", (string)null);
                });

            modelBuilder.Entity("ASO.Domain.Game.Entities.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.ToTable("images", (string)null);
                });

            modelBuilder.Entity("ASO.Domain.Game.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("KeycloakUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("keycloak_user_id");

                    b.Property<int>("TypePlayer")
                        .HasColumnType("integer")
                        .HasColumnName("type_player");

                    b.HasKey("Id");

                    b.HasIndex("KeycloakUserId")
                        .IsUnique();

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("ASO.Domain.Game.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ArmorPenalty")
                        .HasColumnType("boolean")
                        .HasColumnName("armor_penalty");

                    b.Property<int>("KeyAttributes")
                        .HasColumnType("integer")
                        .HasColumnName("key_attributes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<bool>("Trained")
                        .HasColumnType("boolean")
                        .HasColumnName("trained");

                    b.HasKey("Id")
                        .HasName("id");

                    b.ToTable("Skills", (string)null);
                });

            modelBuilder.Entity("ASO.Domain.Identity.Entities.PlayerUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("KeycloakUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("keycloak_user_id");

                    b.HasKey("Id");

                    b.HasIndex("KeycloakUserId")
                        .IsUnique();

                    b.ToTable("player_users", (string)null);
                });

            modelBuilder.Entity("characters_classes", b =>
                {
                    b.Property<Guid>("class_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("character_id")
                        .HasColumnType("uuid");

                    b.HasKey("class_id", "character_id");

                    b.HasIndex("character_id");

                    b.ToTable("characters_classes");
                });

            modelBuilder.Entity("characters_expertises", b =>
                {
                    b.Property<Guid>("expertise_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("character_id")
                        .HasColumnType("uuid");

                    b.HasKey("expertise_id", "character_id");

                    b.HasIndex("character_id");

                    b.ToTable("character_skill", (string)null);
                });

            modelBuilder.Entity("ASO.Domain.AI.Entities.GeneratedAIContent", b =>
                {
                    b.OwnsOne("ASO.Domain.Shared.ValueObjects.Tracker", "Tracker", b1 =>
                        {
                            b1.Property<Guid>("GeneratedAIContentId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at_utc");

                            b1.Property<DateTime>("UpdatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at_utc");

                            b1.HasKey("GeneratedAIContentId");

                            b1.ToTable("generated_AI_content");

                            b1.WithOwner()
                                .HasForeignKey("GeneratedAIContentId");
                        });

                    b.Navigation("Tracker")
                        .IsRequired();
                });

            modelBuilder.Entity("ASO.Domain.Game.Entities.Ancestry", b =>
                {
                    b.OwnsOne("ASO.Domain.Shared.ValueObjects.Tracker", "Tracker", b1 =>
                        {
                            b1.Property<Guid>("AncestryId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at_utc");

                            b1.Property<DateTime>("UpdatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at_utc");

                            b1.HasKey("AncestryId");

                            b1.ToTable("ancestries");

                            b1.WithOwner()
                                .HasForeignKey("AncestryId");
                        });

                    b.Navigation("Tracker")
                        .IsRequired();
                });

            modelBuilder.Entity("ASO.Domain.Game.Entities.Character", b =>
                {
                    b.HasOne("ASO.Domain.Game.Entities.Ancestry", "Ancestry")
                        .WithMany()
                        .HasForeignKey("AncestryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASO.Domain.Game.Entities.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("ASO.Domain.Shared.ValueObjects.Tracker", "Tracker", b1 =>
                        {
                            b1.Property<Guid>("CharacterId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at_utc");

                            b1.Property<DateTime>("UpdatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at_utc");

                            b1.HasKey("CharacterId");

                            b1.ToTable("characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.OwnsOne("ASO.Domain.Game.ValueObjects.AttributeModifiers", "Modifiers", b1 =>
                        {
                            b1.Property<Guid>("CharacterId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ModCharisma")
                                .HasColumnType("integer")
                                .HasColumnName("mod_charisma");

                            b1.Property<int>("ModConstitution")
                                .HasColumnType("integer")
                                .HasColumnName("mod_constitution");

                            b1.Property<int>("ModDexterity")
                                .HasColumnType("integer")
                                .HasColumnName("mod_dexterity");

                            b1.Property<int>("ModIntelligence")
                                .HasColumnType("integer")
                                .HasColumnName("mod_intelligence");

                            b1.Property<int>("ModStrength")
                                .HasColumnType("integer")
                                .HasColumnName("mod_strength");

                            b1.Property<int>("ModWisdom")
                                .HasColumnType("integer")
                                .HasColumnName("mod_wisdom");

                            b1.HasKey("CharacterId");

                            b1.ToTable("characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.Navigation("Ancestry");

                    b.Navigation("Image");

                    b.Navigation("Modifiers")
                        .IsRequired();

                    b.Navigation("Tracker")
                        .IsRequired();
                });

            modelBuilder.Entity("ASO.Domain.Game.Entities.Class", b =>
                {
                    b.OwnsOne("ASO.Domain.Shared.ValueObjects.Tracker", "Tracker", b1 =>
                        {
                            b1.Property<Guid>("ClassId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at_utc");

                            b1.Property<DateTime>("UpdatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at_utc");

                            b1.HasKey("ClassId");

                            b1.ToTable("classes");

                            b1.WithOwner()
                                .HasForeignKey("ClassId");
                        });

                    b.OwnsOne("ASO.Domain.Game.ValueObjects.Statistics", "Statistics", b1 =>
                        {
                            b1.Property<Guid>("ClassId")
                                .HasColumnType("uuid");

                            b1.Property<int>("InitHealthPoints")
                                .HasColumnType("integer")
                                .HasColumnName("init_health_points");

                            b1.Property<int>("InitManaPoints")
                                .HasColumnType("integer")
                                .HasColumnName("init_mana_points");

                            b1.HasKey("ClassId");

                            b1.ToTable("classes");

                            b1.WithOwner()
                                .HasForeignKey("ClassId");
                        });

                    b.Navigation("Statistics")
                        .IsRequired();

                    b.Navigation("Tracker")
                        .IsRequired();
                });

            modelBuilder.Entity("ASO.Domain.Game.Entities.Friendship", b =>
                {
                    b.HasOne("ASO.Domain.Game.Entities.Player", "Addressee")
                        .WithMany("ReceivedFriendRequests")
                        .HasForeignKey("AddresseeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ASO.Domain.Game.Entities.Player", "Requester")
                        .WithMany("SentFriendRequests")
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("ASO.Domain.Shared.ValueObjects.Tracker", "Tracker", b1 =>
                        {
                            b1.Property<Guid>("FriendshipId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<DateTime>("UpdatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.HasKey("FriendshipId");

                            b1.ToTable("friendships");

                            b1.WithOwner()
                                .HasForeignKey("FriendshipId");
                        });

                    b.Navigation("Addressee");

                    b.Navigation("Requester");

                    b.Navigation("Tracker")
                        .IsRequired();
                });

            modelBuilder.Entity("ASO.Domain.Game.Entities.Image", b =>
                {
                    b.OwnsOne("ASO.Domain.Shared.ValueObjects.Tracker", "Tracker", b1 =>
                        {
                            b1.Property<Guid>("ImageId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at_utc");

                            b1.Property<DateTime>("UpdatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at_utc");

                            b1.HasKey("ImageId");

                            b1.ToTable("images");

                            b1.WithOwner()
                                .HasForeignKey("ImageId");
                        });

                    b.Navigation("Tracker")
                        .IsRequired();
                });

            modelBuilder.Entity("ASO.Domain.Game.Entities.Player", b =>
                {
                    b.OwnsOne("ASO.Domain.Shared.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("PlayerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("email");

                            b1.HasKey("PlayerId");

                            b1.HasIndex("Address");

                            b1.ToTable("players");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId");
                        });

                    b.OwnsOne("ASO.Domain.Shared.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("PlayerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("last_name");

                            b1.HasKey("PlayerId");

                            b1.ToTable("players");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId");
                        });

                    b.OwnsOne("ASO.Domain.Shared.ValueObjects.Nickname", "NickName", b1 =>
                        {
                            b1.Property<Guid>("PlayerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Nick")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("nickname");

                            b1.HasKey("PlayerId");

                            b1.ToTable("players");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId");
                        });

                    b.OwnsOne("ASO.Domain.Shared.ValueObjects.Tracker", "Tracker", b1 =>
                        {
                            b1.Property<Guid>("PlayerId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<DateTime>("UpdatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.HasKey("PlayerId");

                            b1.ToTable("players");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("NickName")
                        .IsRequired();

                    b.Navigation("Tracker")
                        .IsRequired();
                });

            modelBuilder.Entity("ASO.Domain.Game.Entities.Skill", b =>
                {
                    b.OwnsOne("ASO.Domain.Shared.ValueObjects.Tracker", "Tracker", b1 =>
                        {
                            b1.Property<Guid>("SkillId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at_utc");

                            b1.Property<DateTime>("UpdatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at_utc");

                            b1.HasKey("SkillId");

                            b1.ToTable("Skills");

                            b1.WithOwner()
                                .HasForeignKey("SkillId");
                        });

                    b.Navigation("Tracker")
                        .IsRequired();
                });

            modelBuilder.Entity("ASO.Domain.Identity.Entities.PlayerUser", b =>
                {
                    b.OwnsOne("ASO.Domain.Shared.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("PlayerUserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("email");

                            b1.HasKey("PlayerUserId");

                            b1.HasIndex("Address");

                            b1.ToTable("player_users");

                            b1.WithOwner()
                                .HasForeignKey("PlayerUserId");
                        });

                    b.OwnsOne("ASO.Domain.Shared.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("PlayerUserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("last_name");

                            b1.HasKey("PlayerUserId");

                            b1.ToTable("player_users");

                            b1.WithOwner()
                                .HasForeignKey("PlayerUserId");
                        });

                    b.OwnsOne("ASO.Domain.Shared.ValueObjects.Nickname", "NickName", b1 =>
                        {
                            b1.Property<Guid>("PlayerUserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Nick")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("nickname");

                            b1.HasKey("PlayerUserId");

                            b1.ToTable("player_users");

                            b1.WithOwner()
                                .HasForeignKey("PlayerUserId");
                        });

                    b.OwnsOne("ASO.Domain.Shared.ValueObjects.Tracker", "Tracker", b1 =>
                        {
                            b1.Property<Guid>("PlayerUserId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<DateTime>("UpdatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.HasKey("PlayerUserId");

                            b1.ToTable("player_users");

                            b1.WithOwner()
                                .HasForeignKey("PlayerUserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("NickName")
                        .IsRequired();

                    b.Navigation("Tracker")
                        .IsRequired();
                });

            modelBuilder.Entity("characters_classes", b =>
                {
                    b.HasOne("ASO.Domain.Game.Entities.Character", null)
                        .WithMany()
                        .HasForeignKey("character_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASO.Domain.Game.Entities.Class", null)
                        .WithMany()
                        .HasForeignKey("class_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("characters_expertises", b =>
                {
                    b.HasOne("ASO.Domain.Game.Entities.Character", null)
                        .WithMany()
                        .HasForeignKey("character_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASO.Domain.Game.Entities.Skill", null)
                        .WithMany()
                        .HasForeignKey("expertise_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ASO.Domain.Game.Entities.Player", b =>
                {
                    b.Navigation("ReceivedFriendRequests");

                    b.Navigation("SentFriendRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
